### ISSUE TITLE
Downsample feature from backbone 

### ISSUE THREAD

**Issue by bluesky314** [romulus0914/EfficientDet-PyTorch#2]
What is this doing in efficentdet model code? 
```
# downsample feature from backbone model to desirable width and channels
        feature_width = image_size // (2**5)
        self.resample6 = _ResampleFeatureMap(feature_width, features_num_channels[-1], feature_width//2, fpn_num_channels)
        self.resample7 = _ResampleFeatureMap(feature_width//2, fpn_num_channels, feature_width//4, fpn_num_channels)
```

I dont see it in offical implementation

**Comment by romulus0914** [comment]
In the official implementation, when collecting the feature maps from the backbone model, it resamples the feature map to desirable resolutions. Since backbone model only provides feature map down to 1/2^5, however, efficientdet requires feature maps down to 1/2^6 and 1/2^7. Therefore, it is required to downsample the feature map of 1/2^5 to desirable resolution.

**Comment by bluesky314** [comment]
Thanks, could you tell me what is 
```
class BiFPN(nn.Module):
    fpn_config = [
        {'width_ratio': 1.0/(2**3), 'inputs': []},
        {'width_ratio': 1.0/(2**4), 'inputs': []},
        {'width_ratio': 1.0/(2**5), 'inputs': []},
        {'width_ratio': 1.0/(2**6), 'inputs': []},
        {'width_ratio': 1.0/(2**7), 'inputs': []},
        {'width_ratio': 1.0/(2**6), 'inputs': [3, 4]},
        {'width_ratio': 1.0/(2**5), 'inputs': [2, 5]},
        {'width_ratio': 1.0/(2**4), 'inputs': [1, 6]},
        {'width_ratio': 1.0/(2**3), 'inputs': [0, 7]},
        {'width_ratio': 1.0/(2**4), 'inputs': [1, 7, 8]},
        {'width_ratio': 1.0/(2**5), 'inputs': [2, 6, 9]},
        {'width_ratio': 1.0/(2**6), 'inputs': [3, 5, 10]},
        {'width_ratio': 1.0/(2**7), 'inputs': [4, 11]},
    ]
```

I was unable to understand even in their offical code, what is 'inputs' supposed to mean? Where do numbers like 9,10,11 come when there are lesser layers in the pyramid

**Comment by romulus0914** [comment]
It is the BiFPN layer config. It’s hard to explain and I suggest to read the paper thoroughly.

**Comment by bluesky314** [comment]
I did read the paper. Could you point me where this is hinted at?

**Comment by romulus0914** [comment]
4 -- - -> 12
3 -> 5 -> 11
2 -> 6 -> 10
1 -> 7 -> 9
0 -- - -> 8

The node index in BiFPN config. Hope you can understand it.

**Comment by bluesky314** [comment]
Thanks a lot :)
