### ISSUE TITLE
MobileNetV2 Block

### ISSUE THREAD

**Issue by bluesky314** [romulus0914/EfficientDet-PyTorch#3]
MobileNetV2 blocks consist of 1X1 convolution-> depthwise sperable convolution->1X1 convolution. However your bifpn only seems to have 1X1 and depthwise and not the last 1X1 as your `_SepconvBnReLU ` only has 2 convs. Even when I print only two show up
<img width="839" alt="Screen Shot 2020-03-26 at 3 18 55 PM" src="https://user-images.githubusercontent.com/35393972/77633359-5c61ee00-6f75-11ea-8f34-a29859b5f2ed.png">

Not only that but also the Squeeze Excitation layers used in EfficientDet paper and their code is missing.

**Comment by romulus0914** [comment]
In my opinion, the official implementation did not use inverted bottle neck layer in BiFPN not the paper mentioned using it. It simply employs depthwise separable convolutions.

**Comment by bluesky314** [comment]
Here is the screenshot of their offical bifpn, there are  SE layers
<img width="919" alt="Screen Shot 2020-03-26 at 3 42 10 PM" src="https://user-images.githubusercontent.com/35393972/77635322-646f5d00-6f78-11ea-875c-d5851f60e51b.png">

**Comment by bluesky314** [comment]
If you want here is a copy to visualise their model: https://colab.research.google.com/drive/1xIcFmGkBDHUqkHW_uLFqQ0Eb_0OUjyCM

**Comment by romulus0914** [comment]
The image is “efficientnet”, not “efficientdet”.

**Comment by bluesky314** [comment]
Sorry my mistake, it seems you are right there are no SE blocks or residuals in bifpn but there are still 3 convolutions, as opposed to your 2:

<img width="962" alt="Screen Shot 2020-03-26 at 3 56 46 PM" src="https://user-images.githubusercontent.com/35393972/77636696-7f42d100-6f7a-11ea-8589-a0308f54b960.png">

**Comment by romulus0914** [comment]
I believe it is the “bias” weight, not actual convolution operation.

**Comment by bluesky314** [comment]
I am pointing out the 
```
fpn_cells/cell_0/fnode2/resample_0_1_7/conv2d/kernel:0 (float32_ref 1x1x112x64) [7168, bytes: 28672]
fpn_cells/cell_0/fnode2/op_after_combine7/conv/depthwise_kernel:0 (float32_ref 3x3x64x1) [576, bytes: 2304]
fpn_cells/cell_0/fnode2/op_after_combine7/conv/pointwise_kernel:0 (float32_ref 1x1x64x64) [4096, bytes: 16384]
```
All 3 are kernals.

**Comment by bluesky314** [comment]
But I observed these are not present in the second, third pyramids only the first so maybe its just getting the encoder shapes to the appropriate channel numbers for the bifpn

**Comment by romulus0914** [comment]
In BiFPN, it requires the feature maps to have same resolution, so some may need resampling before convolution operations.
