### ISSUE TITLE
Segmentation Model

### ISSUE THREAD

**Issue by bluesky314** [romulus0914/EfficientDet-PyTorch#4]
Thanks for your implementation, I wanted to modify your code to make it as segmentation network as suggested in the paper. We have to 

> Following [16], we modify our EfficientDet model to keep feature level {P2,P3,...,P7} in BiFPN, but only use P2 for the fi- nal per-pixel classification. For simplicity, here we only evaluate a EfficientDet-D4 based model, which uses a Ima- geNet pretrained EfficientNet-B4 backbone (similar size to ResNet-50). We set the channel size to 128 for BiFPN and 256 for classification head. Both BiFPN and classification head are repeated by 3 times.

So we have to add one more lower layer from P2 instead of P3 as in the OD case. 
So the pyramid would look like 
5------>15
4 -- 6 -> 14
3 -> 7 -> 13
2 -> 8 -> 12
1 -> 9 -> 11
0 -- - -> 10

Can I know how to modify your code for this pyramid?

**Comment by bluesky314** [comment]
I changed the config to 
```
class BiFPN(nn.Module):
    fpn_config = [
        {'width_ratio': 1.0/(2**2), 'inputs': []}, # new return
        {'width_ratio': 1.0/(2**3), 'inputs': []},
        {'width_ratio': 1.0/(2**4), 'inputs': []},
        {'width_ratio': 1.0/(2**5), 'inputs': []},
        {'width_ratio': 1.0/(2**6), 'inputs': []},
        {'width_ratio': 1.0/(2**7), 'inputs': []},
        {'width_ratio': 1.0/(2**6), 'inputs': [4, 5]},
        {'width_ratio': 1.0/(2**5), 'inputs': [3, 6]},
        {'width_ratio': 1.0/(2**4), 'inputs': [2, 7]},
        {'width_ratio': 1.0/(2**3), 'inputs': [1, 8]}, # middle add
        {'width_ratio': 1.0/(2**2), 'inputs': [0, 9]}, # last add
        {'width_ratio': 1.0/(2**3), 'inputs': [1, 9,10]},
        {'width_ratio': 1.0/(2**4), 'inputs': [2, 8,11]},
        {'width_ratio': 1.0/(2**5), 'inputs': [3, 7, 12]},
        {'width_ratio': 1.0/(2**6), 'inputs': [4, 6, 13]},
        {'width_ratio': 1.0/(2**7), 'inputs': [5, 14]},
    ]

```
And replaced self.fpn_config[5:] to self.fpn_config[6:] in few places. But the pyramid is not correct.
We also have to change that from backbone we get 4 outputs which I have done

**Comment by bluesky314** [comment]
Here is what I did, changes are made with commentes
[efficientdetSeg.py.zip](https://github.com/romulus0914/EfficientDet-PyTorch/files/4394209/efficientdetSeg.py.zip)

**Comment by bluesky314** [comment]
Please help if you can, we have some deployment and I really want to use EfficientDet for it

**Comment by romulus0914** [comment]
What do you mean by the pyramid is not correct?

**Comment by bluesky314** [comment]
I am getting a size error when the connections are being fused

**Comment by bluesky314** [comment]
The error is that _ResampleFeatureMap is not resizing the feature maps to have the same channels so in the first bifpn we are adding one channel of 320 with one of 64

**Comment by romulus0914** [comment]
I believe it's due to the number of channels when building the BiFPN. I have updated my code for more flexibility. It is only required to change the "model_params['num_features']" for different numbers of backbone features. Therefore, there is no need to modify the code but only the configurations.

**Comment by bluesky314** [comment]
Thanks for doing so! Alright so I should now put model_params['num_features'] as 6 instead of the previous 5 and change the config file to the one mentioned above. Let me try this

**Comment by bluesky314** [comment]
On line 240 there is `model_params['num_features'] = 5`. That should be set to user input I think of efficientdet.py

**Comment by romulus0914** [comment]
In EfficientDet, all the config have the same 'num_features', and therefore I put it there. Your can have your own style.

**Comment by bluesky314** [comment]
Ok, so as I said segmentation has 6 nodes from the encoder: 

> we modify our EfficientDet model to keep feature level {P2,P3,...,P7} in BiFPN

I changed it to user input and ran
`model=efficientdet.EfficientDet(efficientdet_model_params['efficientdet-d0'],num_features=6)`

but it gave me size error

> RuntimeError: The size of tensor a (32) must match the size of tensor b (8) at non-singleton dimension 3


I only changed num_features to be an input now. You can see more about error here:https://colab.research.google.com/drive/1CUTREzZzz8WIYMsq8bp3zm8IlE2rqtL9

**Comment by bluesky314** [comment]
I was able to run it. I will build the segmentation model and let you know if I get stuck. Thanks for your support
