### ISSUE TITLE
Modules not part of the model

### ISSUE THREAD

**Issue by bluesky314** [romulus0914/EfficientDet-PyTorch#5]
There is a problem in the way you have designed your bifpn. One of the problem is in:

```
input_nodes_resample.append(_ResampleFeatureMap(
                        fpn_nodes_width[input_node],
                        features_num_channels[input_node] if cell_idx == 0 and input_node < num_features - 2 else fpn_num_channels,
                        fpn_nodes_width[node_idx+num_features],
                        fpn_num_channels
                    )) 
```

but you have used lists in multiple places. You have created a list of modules that you then apply later. This prevents the modules from being modified via nn.Module's utilities. For e.g. I cannot call model.cuda() and have modules in input_notes_resampled also be turned to cuda. This is still a easily fixable problem. The huge problem is that I cannot save those modules automatically with torch.save. So when I load the weights that it has saved the entire bifpn is initialised a new as it does not save the modules in a list automatically.

**Comment by romulus0914** [comment]
All lists can be easily converted to nn.Sequential, which I have updated the code.
